export const SUPPORTED_LANGUAGES = [
	{ code: "arb", label: "العربية (Standard)" },
	{ code: "ar-AE", label: "العربية (الإمارات)" },
	{ code: "nl-BE", label: "Nederlands (België)" },
	{ code: "ca-ES", label: "Català (Espanya)" },
	{ code: "cs-CZ", label: "Čeština (Česko)" },
	{ code: "yue-CN", label: "粵語 (中國)" },
	{ code: "cmn-CN", label: "中文 (中国)" },
	{ code: "da-DK", label: "Dansk (Danmark)" },
	{ code: "nl-NL", label: "Nederlands (Nederland)" },
	{ code: "en-AU", label: "English (Australia)" },
	{ code: "en-GB", label: "English (UK)" },
	{ code: "en-IN", label: "English (India)" },
	{ code: "en-IE", label: "English (Ireland)" },
	{ code: "en-NZ", label: "English (New Zealand)" },
	{ code: "en-SG", label: "English (Singapore)" },
	{ code: "en-ZA", label: "English (South Africa)" },
	{ code: "en-US", label: "English (US)" },
	{ code: "en-GB-WLS", label: "English (Wales)" },
	{ code: "fi-FI", label: "Suomi (Suomi)" },
	{ code: "fr-FR", label: "Français (France)" },
	{ code: "fr-BE", label: "Français (Belgique)" },
	{ code: "fr-CA", label: "Français (Canada)" },
	{ code: "de-DE", label: "Deutsch (Deutschland)" },
	{ code: "de-AT", label: "Deutsch (Österreich)" },
	{ code: "de-CH", label: "Deutsch (Schweiz)" },
	{ code: "hi-IN", label: "हिन्दी (भारत)" },
	{ code: "is-IS", label: "Íslenska (Ísland)" },
	{ code: "it-IT", label: "Italiano (Italia)" },
	{ code: "ja-JP", label: "日本語 (日本)" },
	{ code: "ko-KR", label: "한국어 (대한민국)" },
	{ code: "nb-NO", label: "Norsk Bokmål (Norge)" },
	{ code: "pl-PL", label: "Polski (Polska)" },
	{ code: "pt-BR", label: "Português (Brasil)" },
	{ code: "pt-PT", label: "Português (Portugal)" },
	{ code: "ro-RO", label: "Română (România)" },
	{ code: "ru-RU", label: "Русский (Россия)" },
	{ code: "es-ES", label: "Español (España)" },
	{ code: "es-MX", label: "Español (México)" },
	{ code: "es-US", label: "Español (EE.UU.)" },
	{ code: "sv-SE", label: "Svenska (Sverige)" },
	{ code: "tr-TR", label: "Türkçe (Türkiye)" },
	{ code: "cy-GB", label: "Cymraeg (Cymru)" },
];
